### ISSUE TITLE
Documenting the last mile - iXML in XProc under Maven

### ISSUE THREAD

**Issue by wendellpiez** [nineml/HOWTO#5]
In my day job we have [at least one repository](https://github.com/usnistgov/metaschema-xslt) using XSLT 3.0 under XProc 1.0, calling XML Calabash in Maven. I would like to be able to include an iXML-based parse in such a pipeline. In addition to such merely 'practical' uses I hope also to achieve more academic objectives here: https://github.com/usnistgov/ixml-breadboard.

To start on this - seeing the step defined at https://github.com/ndw/coffeepress I need to know how to

- [ ] Use an iXML-based parser in a pipeline, with realistic examples (such as the [NGAC PML grammar](https://github.com/usnistgov/ixml-breadboard/blob/main/ixml/ngac/ngac-pml.ixml) in the repo cited)
- [ ] Set up and call my parser from XProc (and ideally from XSLT also)
- [ ] Set up and call such an XProc using Maven (and gradle?) and a `bash` script or functional equivalent

Having produced a working example I could contribute back by writing it up.

@ndw kindly assist - where do you recommend I go next: is there an example for me to see and deconstruct?

**Comment by ndw** [comment]
I'll see about publishing an XProc 1.0 version of CoffeePress. I'd been optimistically assuming I'd get 3.0 out before I needed to do that.

**Comment by ndw** [comment]
I've added an XProc example with XML Calabash 1.x. It kind of brute forces its way through the downloads and the classpath setup, but it demonstrates that it works.

**Comment by wendellpiez** [comment]
@ndw, thank you! Where do I find this example?

If there's anything you think I might need to know (or anything special) about Maven etc. aspects, let me know (or I might be back 👿 )

**Comment by ndw** [comment]
In the directory `xproc-1.0` in the repository. It doesn't use Maven, but getting the parts with Maven should be straightforward. Err. Except for the actual extension step because Sonatype is down this weekend so I haven't been able to publish it.

**Comment by ndw** [comment]
The version in Maven is 1.0.3 not 1.0.0. Because reasons.
